apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notejam.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: {{ include "notejam.name" . }}
    app.kubernetes.io/component: {{.Values.labels.component}}
    {{- include "notejam.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "notejam.name" . }}
      app.kubernetes.io/component: {{.Values.labels.component}}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  replicas:  {{.Values.replicas.minNumber }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "notejam.name" . }}
        app.kubernetes.io/component: {{.Values.labels.component}}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      securityContext:
        fsGroup: {{$.Values.securityContext.fsGroup}}
      containers:
      {{- with .Values.images.notejam }}
      - name: {{.containerName}}
        image: "{{ .repository }}:{{ .tag }}"
        imagePullPolicy: {{ .pullPolicy | quote }}
        ports:
        - containerPort: {{.ports.http.port}}
        securityContext:
          runAsUser: {{.securityContext.runAsUser}}
        resources:
          requests:
            cpu: {{.resources.request.cpu}}
            memory: {{.resources.request.memory}}
          limits:
            cpu: {{.resources.limits.cpu}}
            memory: {{.resources.limits.memory}}
      {{- end }}
      imagePullSecrets:
      - name: {{.Values.secret.dockerRegistry}}