apiVersion: v1
kind: Service
metadata:
  name: {{ include "notejam.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: {{ include "notejam.name" . }}
    app.kubernetes.io/component: {{.Values.labels.component}}
    {{- include "notejam.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "notejam.name" . }}
    app.kubernetes.io/component: {{.Values.labels.component}}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- with .Values.images.notejam.ports.http }}
  - name: {{.name}}
    protocol: {{.protocol}}
    port: {{.port}}
  {{- end }}